
---
Welcome!
My name is Andrea Dame and I am a senior undergraduate microbiology major at UMass Amherst. 
This is a rendering of hmtl files from the course repository  (https://github.com/adame101/evogenomics-course) for Evolutionary Genomics & Bioinformatics taught at the University of Massachusetts Amherst in Fall 2020 by Prof. Jeffrey Blanchard

## Labs

### R Basics

* Lab 1 : [Introduction to R and Reproducible Research](Lab1.html)
* Lab 2 : [git, GitHub and Rstudio project](index.html) 
* Lab 3 : [Data Wrangling (Part 1)](Lab3A.html)
* Lab 3 : [Data Wrangling (Part 2)](Lab3B.html)
* Lab 4 : [Data wrangling and graphing COVID-19 reporting data (Part 1)](Lab4.html)
* Lab 4 : [Data wrangling and graphing COVID-19 reporting data (Part 2)](Lab4a.html)
* Lab 5 : [Data wrangling and graphing COVID-19 reporting data (Part 1)](Lab5(part2datavisual).html))
 * Lab 5 : [Data wrangling and graphing COVID-19 reporting data (Part 2)](Lab5.html) 
 * Lab 5 Extra : [Data wrangling and graphing COVID-19 reporting data ](Lab5extra.html) 
* Lab 6 : [Data Maps and Interactive Graphs from the COVID-19 reporting data](Lab6.html) 
* Lab 7 : [RNA-Seq workflow: gene-level exploratory analysis and differential expression](RNAseqLab7.html)
* Lab 8 : [Sequence Alignment, Phylogenetic Analysis and Tree Visualization](Lab8.html)
* Lab 9 : [R Programming-Regular Expressions](Lab9.html)
* Lab 9 Extra : [R Programming-Functions and Control Structures](Lab9x.html)
* Lab 10  : [Population genomics based on high throughput sequencing (HTS)](Lab10.html)
======= 
#REFERENCE
 bibliography: references.bib

